### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by RegisGraptin** [zq99/pgn2data#10]
I am currently interested in using your librairy to parse png file from chess game. 
I am using the [lichess database](https://database.lichess.org/) to get my data.
Unfortunatly, when I try to parse it using `png2data` my RAM constently increase!
I think that the process of reading/writing are maybe not optimized, I think that maybe the data from the read file is still saved.
So for my case, I can't read the total content of a 5GB pgn file.

**Comment by RegisGraptin** [comment]
It seems that it is a concurrency issues.
When you create the worker, the limit is set to 0, indicating an infinite size. In `process.py`
```python
q = queue.Queue(maxsize=0)
worker = Thread(target=self.__process_move_queue, args=(q,))
```
I think this is the cause of the issus I have. So, it might be interesting to add a maximum value as default, to be sure that the elements in the queue are processed.

**Comment by zq99** [comment]
Thanks for investigating and highlighting this issue.

The latest version (v.0.0.9) has queue size as an optional parameter in the export method: 

`from converter.pgn_data import PGNData

filename = 'caruana_carlsen_2018.pgn'
pgn_data = PGNData(filename)
result = pgn_data.export(queue_size=1000)
`

This makes it easier to fit in the testing framework. Hopefully, this gives enough flexibility to overcome this memory issue.
