### ISSUE TITLE
Illegal moves exit execution

### ISSUE THREAD

**Issue by Prog-Jacob** [zq99/pgn2data#3]
When a game within a pgn has an illegal move or a character the codec can't encode, it breaks the whole execution. It seems python-chess raised the error. I handled this issue while working with chess.pgn using:

try:
    game = chess.pgn.read_game(pgn_file)
except:
    continue

Btw, so much of a great work, you saved me a ton of work:)

**Comment by zq99** [comment]
Hi, do you have an example of a pgn file or game that generates this issue? Thanks

**Comment by zq99** [comment]
I think the latest release will have resolved this issue.
