### ISSUE TITLE
pgn files where the moves are missing and replaced with a dash, causes the process to stop

### ISSUE THREAD

**Issue by zq99** [zq99/pgn2data#4]
If a game has moves that are missing and the move is just a '-', the process crashes with the error:

ValueError: '00' is not in list

This zip file contains an example of a pgn file with missing moves:
[missing_moves.zip](https://github.com/zq99/pgn2data/files/9673246/missing_moves.zip)

**Comment by ktadgh** [comment]
Hey Zaid, I've submitted a PR, let me know if you get a chance to review it.

**Comment by zq99** [comment]
The latest release has the fixes for this. Thank you @ktadgh for your help.
