### ISSUE TITLE
Only export game_info

### ISSUE THREAD

**Issue by davidwozabal** [zq99/pgn2data#6]
I am reading in quite large files and would only require the game_info (not the moves). It would be great if there was an option in the export method to only read the game_info and not the moves.

This would save a lot of disk-space for larger files and possible also speed up the routine.

**Comment by zq99** [comment]
The latest version v.0.0.9 has this functionality

`pgn_data = PGNData('chess_games.pgn')

result = pgn_data.export(moves_required=False)`
